# Generated by Django 5.2.3 on 2025-07-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
