# Generated by Django 5.2.3 on 2025-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication",
            field=models.BooleanField(default=False, verbose_name="Публиковано"),
        ),
    ]
